# Uncomment the next line to define a global platform for your project

platform :ios, '10.0'

target 'MVP' do

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'iOSLoader', '~> 0.0.6'    # comment cocoaPodLink

  pod 'ImageCacheiOS', '~> 0.0.2'     # comment cocoaPodLink

  pod 'iOSHTTPConnect', '~> 0.0.9'    # comment cocoaPodLink

  pod 'iOSCoreDataConnect', '~> 0.0.2'    # comment cocoaPodLink

 # pod 'iOSHTTPConnect', :path => '/Users/chandrakant/Desktop/R&D/iOSHTTPConnect' 


  # Pods for MVP

  target 'MVPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVPUITests' do
    # Pods for testing
  end

end
