# Uncomment the next line to define a global platform for your project

platform :ios, '10.0'

target 'MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM

  pod 'iOSLoader', '~> 0.0.6'    # comment cocoaPodLink

  pod 'ImageCacheiOS', '~> 0.0.2'     # comment cocoaPodLink

  pod 'iOSHTTPConnect', '~> 0.0.10'    # comment cocoaPodLink

  pod 'iOSCoreDataConnect', '~> 0.0.2'    # comment cocoaPodLink

 # pod 'iOSHTTPConnect', :path => '/Users/chandrakant/Desktop/R&D/iOSHTTPConnect' 


  target 'MVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMUITests' do
    # Pods for testing
  end

end